//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTIC_IT.Resources.Views.Layout.layout", typeof(layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Content/banners/banner_principal_eng.jpg.
        /// </summary>
        public static string bannerprincipal {
            get {
                return ResourceManager.GetString("bannerprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job Offer.
        /// </summary>
        public static string criaroferta {
            get {
                return ResourceManager.GetString("criaroferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my Companies.
        /// </summary>
        public static string gerirasminhasempresas {
            get {
                return ResourceManager.GetString("gerirasminhasempresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my Job Ads.
        /// </summary>
        public static string gerirosmeusanuncios {
            get {
                return ResourceManager.GetString("gerirosmeusanuncios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of job vacancies.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job offers.
        /// </summary>
        public static string jobofeers {
            get {
                return ResourceManager.GetString("jobofeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Itjobs.
        /// </summary>
        public static string meuspecialone {
            get {
                return ResourceManager.GetString("meuspecialone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Companies.
        /// </summary>
        public static string MinhasEmpresa {
            get {
                return ResourceManager.GetString("MinhasEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Search.
        /// </summary>
        public static string pesquisa {
            get {
                return ResourceManager.GetString("pesquisa", resourceCulture);
            }
        }
    }
}
