//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Anuncios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Anuncios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTIC_IT.Resources.ViewModels.Anuncios.Anuncios", typeof(Anuncios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create job offer.
        /// </summary>
        public static string criaoferta {
            get {
                return ResourceManager.GetString("criaoferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot have more than 4000 characters.
        /// </summary>
        public static string descricaoover4000 {
            get {
                return ResourceManager.GetString("descricaoover4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is required.
        /// </summary>
        public static string descricaorequired {
            get {
                return ResourceManager.GetString("descricaorequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string email_required {
            get {
                return ResourceManager.GetString("email_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company is required, go to MyCompanies to create a new one.
        /// </summary>
        public static string empresa_required {
            get {
                return ResourceManager.GetString("empresa_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Workplace is required.
        /// </summary>
        public static string local_de_trabalho_required {
            get {
                return ResourceManager.GetString("local_de_trabalho_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the company is required.
        /// </summary>
        public static string nome_da_empresa_required {
            get {
                return ResourceManager.GetString("nome_da_empresa_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Salary is required.
        /// </summary>
        public static string salario_required {
            get {
                return ResourceManager.GetString("salario_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot have more than 200 characters.
        /// </summary>
        public static string titulo200 {
            get {
                return ResourceManager.GetString("titulo200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title  is required.
        /// </summary>
        public static string titulorequired {
            get {
                return ResourceManager.GetString("titulorequired", resourceCulture);
            }
        }
    }
}
