//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("UKModel", "FK_anuncio_empresa", "empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfITUK.empresa), "anuncio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfITUK.anuncio), true)]
[assembly: EdmRelationshipAttribute("UKModel", "FK_anunciodesc_anuncio", "anuncio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfITUK.anuncio), "anunciodesc", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfITUK.anunciodesc), true)]
[assembly: EdmRelationshipAttribute("UKModel", "FK_anunciodesc_idiomas", "idiomas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WcfITUK.idiomas), "anunciodesc", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WcfITUK.anunciodesc), true)]

#endregion

namespace WcfITUK
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UKEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UKEntities object using the connection string found in the 'UKEntities' section of the application configuration file.
        /// </summary>
        public UKEntities() : base("name=UKEntities", "UKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UKEntities object.
        /// </summary>
        public UKEntities(string connectionString) : base(connectionString, "UKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UKEntities object.
        /// </summary>
        public UKEntities(EntityConnection connection) : base(connection, "UKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<anuncio> anuncio
        {
            get
            {
                if ((_anuncio == null))
                {
                    _anuncio = base.CreateObjectSet<anuncio>("anuncio");
                }
                return _anuncio;
            }
        }
        private ObjectSet<anuncio> _anuncio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<anunciodesc> anunciodesc
        {
            get
            {
                if ((_anunciodesc == null))
                {
                    _anunciodesc = base.CreateObjectSet<anunciodesc>("anunciodesc");
                }
                return _anunciodesc;
            }
        }
        private ObjectSet<anunciodesc> _anunciodesc;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<empresa> empresa
        {
            get
            {
                if ((_empresa == null))
                {
                    _empresa = base.CreateObjectSet<empresa>("empresa");
                }
                return _empresa;
            }
        }
        private ObjectSet<empresa> _empresa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<idiomas> idiomas
        {
            get
            {
                if ((_idiomas == null))
                {
                    _idiomas = base.CreateObjectSet<idiomas>("idiomas");
                }
                return _idiomas;
            }
        }
        private ObjectSet<idiomas> _idiomas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the anuncio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToanuncio(anuncio anuncio)
        {
            base.AddObject("anuncio", anuncio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the anunciodesc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToanunciodesc(anunciodesc anunciodesc)
        {
            base.AddObject("anunciodesc", anunciodesc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the empresa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToempresa(empresa empresa)
        {
            base.AddObject("empresa", empresa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the idiomas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToidiomas(idiomas idiomas)
        {
            base.AddObject("idiomas", idiomas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UKModel", Name="anuncio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class anuncio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new anuncio object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="dataanuncio">Initial value of the dataanuncio property.</param>
        /// <param name="empresa_id">Initial value of the empresa_id property.</param>
        /// <param name="local_de_trabalho">Initial value of the local_de_trabalho property.</param>
        /// <param name="salario">Initial value of the salario property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="identidade">Initial value of the identidade property.</param>
        /// <param name="numvisitas">Initial value of the numvisitas property.</param>
        public static anuncio Createanuncio(global::System.Int32 id, global::System.DateTime dataanuncio, global::System.Int32 empresa_id, global::System.String local_de_trabalho, global::System.String salario, global::System.String email, global::System.String identidade, global::System.Int32 numvisitas)
        {
            anuncio anuncio = new anuncio();
            anuncio.id = id;
            anuncio.dataanuncio = dataanuncio;
            anuncio.empresa_id = empresa_id;
            anuncio.local_de_trabalho = local_de_trabalho;
            anuncio.salario = salario;
            anuncio.email = email;
            anuncio.identidade = identidade;
            anuncio.numvisitas = numvisitas;
            return anuncio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataanuncio
        {
            get
            {
                return _dataanuncio;
            }
            set
            {
                OndataanuncioChanging(value);
                ReportPropertyChanging("dataanuncio");
                _dataanuncio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataanuncio");
                OndataanuncioChanged();
            }
        }
        private global::System.DateTime _dataanuncio;
        partial void OndataanuncioChanging(global::System.DateTime value);
        partial void OndataanuncioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 empresa_id
        {
            get
            {
                return _empresa_id;
            }
            set
            {
                Onempresa_idChanging(value);
                ReportPropertyChanging("empresa_id");
                _empresa_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("empresa_id");
                Onempresa_idChanged();
            }
        }
        private global::System.Int32 _empresa_id;
        partial void Onempresa_idChanging(global::System.Int32 value);
        partial void Onempresa_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String local_de_trabalho
        {
            get
            {
                return _local_de_trabalho;
            }
            set
            {
                Onlocal_de_trabalhoChanging(value);
                ReportPropertyChanging("local_de_trabalho");
                _local_de_trabalho = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("local_de_trabalho");
                Onlocal_de_trabalhoChanged();
            }
        }
        private global::System.String _local_de_trabalho;
        partial void Onlocal_de_trabalhoChanging(global::System.String value);
        partial void Onlocal_de_trabalhoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salario
        {
            get
            {
                return _salario;
            }
            set
            {
                OnsalarioChanging(value);
                ReportPropertyChanging("salario");
                _salario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salario");
                OnsalarioChanged();
            }
        }
        private global::System.String _salario;
        partial void OnsalarioChanging(global::System.String value);
        partial void OnsalarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String identidade
        {
            get
            {
                return _identidade;
            }
            set
            {
                OnidentidadeChanging(value);
                ReportPropertyChanging("identidade");
                _identidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("identidade");
                OnidentidadeChanged();
            }
        }
        private global::System.String _identidade;
        partial void OnidentidadeChanging(global::System.String value);
        partial void OnidentidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numvisitas
        {
            get
            {
                return _numvisitas;
            }
            set
            {
                OnnumvisitasChanging(value);
                ReportPropertyChanging("numvisitas");
                _numvisitas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numvisitas");
                OnnumvisitasChanged();
            }
        }
        private global::System.Int32 _numvisitas;
        partial void OnnumvisitasChanging(global::System.Int32 value);
        partial void OnnumvisitasChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anuncio_empresa", "empresa")]
        public empresa empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("UKModel.FK_anuncio_empresa", "empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("UKModel.FK_anuncio_empresa", "empresa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresa> empresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("UKModel.FK_anuncio_empresa", "empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresa>("UKModel.FK_anuncio_empresa", "empresa", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anunciodesc_anuncio", "anunciodesc")]
        public EntityCollection<anunciodesc> anunciodesc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<anunciodesc>("UKModel.FK_anunciodesc_anuncio", "anunciodesc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<anunciodesc>("UKModel.FK_anunciodesc_anuncio", "anunciodesc", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UKModel", Name="anunciodesc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class anunciodesc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new anunciodesc object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="idioma_id">Initial value of the idioma_id property.</param>
        /// <param name="anuncio_id">Initial value of the anuncio_id property.</param>
        public static anunciodesc Createanunciodesc(global::System.Int32 id, global::System.String titulo, global::System.String descricao, global::System.Int32 idioma_id, global::System.Int32 anuncio_id)
        {
            anunciodesc anunciodesc = new anunciodesc();
            anunciodesc.id = id;
            anunciodesc.titulo = titulo;
            anunciodesc.descricao = descricao;
            anunciodesc.idioma_id = idioma_id;
            anunciodesc.anuncio_id = anuncio_id;
            return anunciodesc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idioma_id
        {
            get
            {
                return _idioma_id;
            }
            set
            {
                Onidioma_idChanging(value);
                ReportPropertyChanging("idioma_id");
                _idioma_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idioma_id");
                Onidioma_idChanged();
            }
        }
        private global::System.Int32 _idioma_id;
        partial void Onidioma_idChanging(global::System.Int32 value);
        partial void Onidioma_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 anuncio_id
        {
            get
            {
                return _anuncio_id;
            }
            set
            {
                Onanuncio_idChanging(value);
                ReportPropertyChanging("anuncio_id");
                _anuncio_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anuncio_id");
                Onanuncio_idChanged();
            }
        }
        private global::System.Int32 _anuncio_id;
        partial void Onanuncio_idChanging(global::System.Int32 value);
        partial void Onanuncio_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anunciodesc_anuncio", "anuncio")]
        public anuncio anuncio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<anuncio>("UKModel.FK_anunciodesc_anuncio", "anuncio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<anuncio>("UKModel.FK_anunciodesc_anuncio", "anuncio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<anuncio> anuncioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<anuncio>("UKModel.FK_anunciodesc_anuncio", "anuncio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<anuncio>("UKModel.FK_anunciodesc_anuncio", "anuncio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anunciodesc_idiomas", "idiomas")]
        public idiomas idiomas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<idiomas>("UKModel.FK_anunciodesc_idiomas", "idiomas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<idiomas>("UKModel.FK_anunciodesc_idiomas", "idiomas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<idiomas> idiomasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<idiomas>("UKModel.FK_anunciodesc_idiomas", "idiomas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<idiomas>("UKModel.FK_anunciodesc_idiomas", "idiomas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UKModel", Name="empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new empresa object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        public static empresa Createempresa(global::System.Int32 id, global::System.String username)
        {
            empresa empresa = new empresa();
            empresa.id = id;
            empresa.username = username;
            return empresa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome_da_empresa
        {
            get
            {
                return _nome_da_empresa;
            }
            set
            {
                Onnome_da_empresaChanging(value);
                ReportPropertyChanging("nome_da_empresa");
                _nome_da_empresa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome_da_empresa");
                Onnome_da_empresaChanged();
            }
        }
        private global::System.String _nome_da_empresa;
        partial void Onnome_da_empresaChanging(global::System.String value);
        partial void Onnome_da_empresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logo
        {
            get
            {
                return _logo;
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.String _logo;
        partial void OnlogoChanging(global::System.String value);
        partial void OnlogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contacto
        {
            get
            {
                return _contacto;
            }
            set
            {
                OncontactoChanging(value);
                ReportPropertyChanging("contacto");
                _contacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contacto");
                OncontactoChanged();
            }
        }
        private global::System.String _contacto;
        partial void OncontactoChanging(global::System.String value);
        partial void OncontactoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anuncio_empresa", "anuncio")]
        public EntityCollection<anuncio> anuncio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<anuncio>("UKModel.FK_anuncio_empresa", "anuncio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<anuncio>("UKModel.FK_anuncio_empresa", "anuncio", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UKModel", Name="idiomas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class idiomas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new idiomas object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="lang_code">Initial value of the lang_code property.</param>
        public static idiomas Createidiomas(global::System.Int32 id, global::System.String lang_code)
        {
            idiomas idiomas = new idiomas();
            idiomas.id = id;
            idiomas.lang_code = lang_code;
            return idiomas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lang_code
        {
            get
            {
                return _lang_code;
            }
            set
            {
                Onlang_codeChanging(value);
                ReportPropertyChanging("lang_code");
                _lang_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lang_code");
                Onlang_codeChanged();
            }
        }
        private global::System.String _lang_code;
        partial void Onlang_codeChanging(global::System.String value);
        partial void Onlang_codeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UKModel", "FK_anunciodesc_idiomas", "anunciodesc")]
        public EntityCollection<anunciodesc> anunciodesc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<anunciodesc>("UKModel.FK_anunciodesc_idiomas", "anunciodesc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<anunciodesc>("UKModel.FK_anunciodesc_idiomas", "anunciodesc", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UKModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
