//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTIC_IT.Resources.Views.Account.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete your Account.
        /// </summary>
        public static string apagaconta {
            get {
                return ResourceManager.GetString("apagaconta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string apagarconta {
            get {
                return ResourceManager.GetString("apagarconta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters in length..
        /// </summary>
        public static string caracteres {
            get {
                return ResourceManager.GetString("caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string changepassword {
            get {
                return ResourceManager.GetString("changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string createnewaccount {
            get {
                return ResourceManager.GetString("createnewaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string criacaodacontasemsucesso {
            get {
                return ResourceManager.GetString("criacaodacontasemsucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string enterlogpass {
            get {
                return ResourceManager.GetString("enterlogpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending your password.
        /// </summary>
        public static string erroaoenviarpassword {
            get {
                return ResourceManager.GetString("erroaoenviarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error recovering de password.
        /// </summary>
        public static string erroaorecuperapassword {
            get {
                return ResourceManager.GetString("erroaorecuperapassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget the password.
        /// </summary>
        public static string forgetpass {
            get {
                return ResourceManager.GetString("forgetpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        public static string formbelow {
            get {
                return ResourceManager.GetString("formbelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form.
        /// </summary>
        public static string formderegisto {
            get {
                return ResourceManager.GetString("formderegisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my Account.
        /// </summary>
        public static string geriraminhaconta {
            get {
                return ResourceManager.GetString("geriraminhaconta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string infodaconta {
            get {
                return ResourceManager.GetString("infodaconta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string lembratedemim {
            get {
                return ResourceManager.GetString("lembratedemim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Form.
        /// </summary>
        public static string loginform {
            get {
                return ResourceManager.GetString("loginform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string loginsemsucesso {
            get {
                return ResourceManager.GetString("loginsemsucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string mudarpassword {
            get {
                return ResourceManager.GetString("mudarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string naotemconta {
            get {
                return ResourceManager.GetString("naotemconta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of.
        /// </summary>
        public static string newpasswords {
            get {
                return ResourceManager.GetString("newpasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string oldpassword {
            get {
                return ResourceManager.GetString("oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string passalterada {
            get {
                return ResourceManager.GetString("passalterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of.
        /// </summary>
        public static string passrequired {
            get {
                return ResourceManager.GetString("passrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string passsemsuccesso {
            get {
                return ResourceManager.GetString("passsemsuccesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password with Email.
        /// </summary>
        public static string recuperaporemail {
            get {
                return ResourceManager.GetString("recuperaporemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string recuperarpass {
            get {
                return ResourceManager.GetString("recuperarpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you lost the password.
        /// </summary>
        public static string seperdeuapassword {
            get {
                return ResourceManager.GetString("seperdeuapassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success sending the password.
        /// </summary>
        public static string sucessoaoenviarapassword {
            get {
                return ResourceManager.GetString("sucessoaoenviarapassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        public static string useformcreate {
            get {
                return ResourceManager.GetString("useformcreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User administration.
        /// </summary>
        public static string useradmin {
            get {
                return ResourceManager.GetString("useradmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
