//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTIC_IT.ServiceRefAlemanha {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnuncioModel", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha")]
    [System.SerializableAttribute()]
    public partial class AnuncioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataanuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Local_de_trabalhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumvisitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dataanuncio {
            get {
                return this.DataanuncioField;
            }
            set {
                if ((this.DataanuncioField.Equals(value) != true)) {
                    this.DataanuncioField = value;
                    this.RaisePropertyChanged("Dataanuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identidade {
            get {
                return this.IdentidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentidadeField, value) != true)) {
                    this.IdentidadeField = value;
                    this.RaisePropertyChanged("Identidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Local_de_trabalho {
            get {
                return this.Local_de_trabalhoField;
            }
            set {
                if ((object.ReferenceEquals(this.Local_de_trabalhoField, value) != true)) {
                    this.Local_de_trabalhoField = value;
                    this.RaisePropertyChanged("Local_de_trabalho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numvisitas {
            get {
                return this.NumvisitasField;
            }
            set {
                if ((this.NumvisitasField.Equals(value) != true)) {
                    this.NumvisitasField = value;
                    this.RaisePropertyChanged("Numvisitas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((object.ReferenceEquals(this.SalarioField, value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DescricaoModel", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha")]
    [System.SerializableAttribute()]
    public partial class DescricaoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Anuncio_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Idioma_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anuncio_id {
            get {
                return this.Anuncio_idField;
            }
            set {
                if ((this.Anuncio_idField.Equals(value) != true)) {
                    this.Anuncio_idField = value;
                    this.RaisePropertyChanged("Anuncio_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idioma_id {
            get {
                return this.Idioma_idField;
            }
            set {
                if ((this.Idioma_idField.Equals(value) != true)) {
                    this.Idioma_idField = value;
                    this.RaisePropertyChanged("Idioma_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="empresa", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class empresa : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.anuncio[] anuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nome_da_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.anuncio[] anuncio {
            get {
                return this.anuncioField;
            }
            set {
                this.anuncioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome_da_empresa {
            get {
                return this.nome_da_empresaField;
            }
            set {
                this.nome_da_empresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="anuncio", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class anuncio : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] anunciodescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataanuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.empresa empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.empresa> empresaReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empresa_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string local_de_trabalhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numvisitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] anunciodesc {
            get {
                return this.anunciodescField;
            }
            set {
                this.anunciodescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataanuncio {
            get {
                return this.dataanuncioField;
            }
            set {
                this.dataanuncioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.empresa empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.empresa> empresaReference {
            get {
                return this.empresaReferenceField;
            }
            set {
                this.empresaReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empresa_id {
            get {
                return this.empresa_idField;
            }
            set {
                this.empresa_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identidade {
            get {
                return this.identidadeField;
            }
            set {
                this.identidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string local_de_trabalho {
            get {
                return this.local_de_trabalhoField;
            }
            set {
                this.local_de_trabalhoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numvisitas {
            get {
                return this.numvisitasField;
            }
            set {
                this.numvisitasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salario {
            get {
                return this.salarioField;
            }
            set {
                this.salarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="anunciodesc", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class anunciodesc : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.anuncio anuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.anuncio> anuncioReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int anuncio_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idioma_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.idiomas idiomasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.idiomas> idiomasReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.anuncio anuncio {
            get {
                return this.anuncioField;
            }
            set {
                this.anuncioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.anuncio> anuncioReference {
            get {
                return this.anuncioReferenceField;
            }
            set {
                this.anuncioReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int anuncio_id {
            get {
                return this.anuncio_idField;
            }
            set {
                this.anuncio_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idioma_id {
            get {
                return this.idioma_idField;
            }
            set {
                this.idioma_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.idiomas idiomas {
            get {
                return this.idiomasField;
            }
            set {
                this.idiomasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.idiomas> idiomasReference {
            get {
                return this.idiomasReferenceField;
            }
            set {
                this.idiomasReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="idiomas", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class idiomas : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] anunciodescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lang_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] anunciodesc {
            get {
                return this.anunciodescField;
            }
            set {
                this.anunciodescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang_code {
            get {
                return this.lang_codeField;
            }
            set {
                this.lang_codeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortugalViewModel", Namespace="http://schemas.datacontract.org/2004/07/WcfITPortugal.Viewmodels")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.AnuncioModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.DescricaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.empresa[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anuncio[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anuncio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anunciodesc[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anunciodesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.idiomas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.EmpresaModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.anuncio>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.idiomas>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.empresa>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember))]
    public partial class PortugalViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SearchResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int anuncio_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataanuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empresa_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idioma_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string local_de_trabalhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numvisitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SearchResults {
            get {
                return this.SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchResultsField, value) != true)) {
                    this.SearchResultsField = value;
                    this.RaisePropertyChanged("SearchResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int anuncio_id {
            get {
                return this.anuncio_idField;
            }
            set {
                if ((this.anuncio_idField.Equals(value) != true)) {
                    this.anuncio_idField = value;
                    this.RaisePropertyChanged("anuncio_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataanuncio {
            get {
                return this.dataanuncioField;
            }
            set {
                if ((this.dataanuncioField.Equals(value) != true)) {
                    this.dataanuncioField = value;
                    this.RaisePropertyChanged("dataanuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empresa_id {
            get {
                return this.empresa_idField;
            }
            set {
                if ((this.empresa_idField.Equals(value) != true)) {
                    this.empresa_idField = value;
                    this.RaisePropertyChanged("empresa_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identidade {
            get {
                return this.identidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.identidadeField, value) != true)) {
                    this.identidadeField = value;
                    this.RaisePropertyChanged("identidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idioma_id {
            get {
                return this.idioma_idField;
            }
            set {
                if ((this.idioma_idField.Equals(value) != true)) {
                    this.idioma_idField = value;
                    this.RaisePropertyChanged("idioma_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string local_de_trabalho {
            get {
                return this.local_de_trabalhoField;
            }
            set {
                if ((object.ReferenceEquals(this.local_de_trabalhoField, value) != true)) {
                    this.local_de_trabalhoField = value;
                    this.RaisePropertyChanged("local_de_trabalho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numvisitas {
            get {
                return this.numvisitasField;
            }
            set {
                if ((this.numvisitasField.Equals(value) != true)) {
                    this.numvisitasField = value;
                    this.RaisePropertyChanged("numvisitas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salario {
            get {
                return this.salarioField;
            }
            set {
                if ((object.ReferenceEquals(this.salarioField, value) != true)) {
                    this.salarioField = value;
                    this.RaisePropertyChanged("salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPortugalViewModel", Namespace="http://schemas.datacontract.org/2004/07/WcfITPortugal.Viewmodels")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.AnuncioModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.DescricaoModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.empresa[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anuncio[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anuncio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anunciodesc[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.anunciodesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.idiomas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MvcTIC_IT.ServiceRefAlemanha.EmpresaModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.anuncio>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.idiomas>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference<MvcTIC_IT.ServiceRefAlemanha.empresa>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember))]
    public partial class SearchPortugalViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SearchResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int anuncio_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dataanuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empresa_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idioma_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string local_de_trabalhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numvisitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SearchResults {
            get {
                return this.SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchResultsField, value) != true)) {
                    this.SearchResultsField = value;
                    this.RaisePropertyChanged("SearchResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int anuncio_id {
            get {
                return this.anuncio_idField;
            }
            set {
                if ((this.anuncio_idField.Equals(value) != true)) {
                    this.anuncio_idField = value;
                    this.RaisePropertyChanged("anuncio_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataanuncio {
            get {
                return this.dataanuncioField;
            }
            set {
                if ((this.dataanuncioField.Equals(value) != true)) {
                    this.dataanuncioField = value;
                    this.RaisePropertyChanged("dataanuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empresa_id {
            get {
                return this.empresa_idField;
            }
            set {
                if ((this.empresa_idField.Equals(value) != true)) {
                    this.empresa_idField = value;
                    this.RaisePropertyChanged("empresa_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identidade {
            get {
                return this.identidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.identidadeField, value) != true)) {
                    this.identidadeField = value;
                    this.RaisePropertyChanged("identidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idioma_id {
            get {
                return this.idioma_idField;
            }
            set {
                if ((this.idioma_idField.Equals(value) != true)) {
                    this.idioma_idField = value;
                    this.RaisePropertyChanged("idioma_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string local_de_trabalho {
            get {
                return this.local_de_trabalhoField;
            }
            set {
                if ((object.ReferenceEquals(this.local_de_trabalhoField, value) != true)) {
                    this.local_de_trabalhoField = value;
                    this.RaisePropertyChanged("local_de_trabalho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numvisitas {
            get {
                return this.numvisitasField;
            }
            set {
                if ((this.numvisitasField.Equals(value) != true)) {
                    this.numvisitasField = value;
                    this.RaisePropertyChanged("numvisitas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salario {
            get {
                return this.salarioField;
            }
            set {
                if ((object.ReferenceEquals(this.salarioField, value) != true)) {
                    this.salarioField = value;
                    this.RaisePropertyChanged("salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaModel", Namespace="http://schemas.datacontract.org/2004/07/WcfITAlemanha")]
    [System.SerializableAttribute()]
    public partial class EmpresaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nome_da_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome_da_empresa {
            get {
                return this.Nome_da_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nome_da_empresaField, value) != true)) {
                    this.Nome_da_empresaField = value;
                    this.RaisePropertyChanged("Nome_da_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefAlemanha.IServiceAlemanha")]
    public interface IServiceAlemanha {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetData", ReplyAction="http://tempuri.org/IServiceAlemanha/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAlemanha/GetDataUsingDataContractResponse")]
        MvcTIC_IT.ServiceRefAlemanha.CompositeType GetDataUsingDataContract(MvcTIC_IT.ServiceRefAlemanha.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/AddAnuncioModel", ReplyAction="http://tempuri.org/IServiceAlemanha/AddAnuncioModelResponse")]
        int AddAnuncioModel(MvcTIC_IT.ServiceRefAlemanha.AnuncioModel anuncio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/AddDescricao", ReplyAction="http://tempuri.org/IServiceAlemanha/AddDescricaoResponse")]
        bool AddDescricao(MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetIdioma_ID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetIdioma_IDResponse")]
        int GetIdioma_ID(string idiomacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAllEmpresaByID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAllEmpresaByIDResponse")]
        MvcTIC_IT.ServiceRefAlemanha.empresa[] GetAllEmpresaByID(string identidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAllAnunciosID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAllAnunciosIDResponse")]
        MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[] GetAllAnunciosID(string idiomacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/UpdateVisitasAnuncioPortugal", ReplyAction="http://tempuri.org/IServiceAlemanha/UpdateVisitasAnuncioPortugalResponse")]
        void UpdateVisitasAnuncioPortugal(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAnunciosProcuraIndexByID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAnunciosProcuraIndexByIDResponse")]
        MvcTIC_IT.ServiceRefAlemanha.anuncio GetAnunciosProcuraIndexByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAnunciosDescProcuraIndexByIDAndLangCode", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAnunciosDescProcuraIndexByIDAndLangCodeRes" +
            "ponse")]
        MvcTIC_IT.ServiceRefAlemanha.anunciodesc GetAnunciosDescProcuraIndexByIDAndLangCode(int id, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetCountIdiomas", ReplyAction="http://tempuri.org/IServiceAlemanha/GetCountIdiomasResponse")]
        int GetCountIdiomas(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAnunciosDescProcuraIndexByIDALL", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAnunciosDescProcuraIndexByIDALLResponse")]
        MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] GetAnunciosDescProcuraIndexByIDALL(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAnunciosIndexByIdentidade", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAnunciosIndexByIdentidadeResponse")]
        MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[] GetAnunciosIndexByIdentidade(string user, string idiomacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAllEmpresaByEmpresaID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAllEmpresaByEmpresaIDResponse")]
        MvcTIC_IT.ServiceRefAlemanha.empresa GetAllEmpresaByEmpresaID(int empresa_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/AddEmpresa", ReplyAction="http://tempuri.org/IServiceAlemanha/AddEmpresaResponse")]
        int AddEmpresa(MvcTIC_IT.ServiceRefAlemanha.EmpresaModel desc);
        
        // CODEGEN: Generating message contract since the operation Upload is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/Upload", ReplyAction="http://tempuri.org/IServiceAlemanha/UploadResponse")]
        MvcTIC_IT.ServiceRefAlemanha.UploadResponse Upload(MvcTIC_IT.ServiceRefAlemanha.StreamData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/UpdateImage_file", ReplyAction="http://tempuri.org/IServiceAlemanha/UpdateImage_fileResponse")]
        void UpdateImage_file(int id, string file_name_fto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetEmpresasIndexByIdentidade", ReplyAction="http://tempuri.org/IServiceAlemanha/GetEmpresasIndexByIdentidadeResponse")]
        MvcTIC_IT.ServiceRefAlemanha.empresa[] GetEmpresasIndexByIdentidade(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/UpdateEmpresa", ReplyAction="http://tempuri.org/IServiceAlemanha/UpdateEmpresaResponse")]
        void UpdateEmpresa(int id, MvcTIC_IT.ServiceRefAlemanha.EmpresaModel desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetEmpresaIndexByID", ReplyAction="http://tempuri.org/IServiceAlemanha/GetEmpresaIndexByIDResponse")]
        MvcTIC_IT.ServiceRefAlemanha.empresa GetEmpresaIndexByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/DeleteEmpresa", ReplyAction="http://tempuri.org/IServiceAlemanha/DeleteEmpresaResponse")]
        void DeleteEmpresa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/DeleteAnuncio", ReplyAction="http://tempuri.org/IServiceAlemanha/DeleteAnuncioResponse")]
        void DeleteAnuncio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/Save", ReplyAction="http://tempuri.org/IServiceAlemanha/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetEmpresasTodasasEmpresas", ReplyAction="http://tempuri.org/IServiceAlemanha/GetEmpresasTodasasEmpresasResponse")]
        MvcTIC_IT.ServiceRefAlemanha.empresa[] GetEmpresasTodasasEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/UpdateAnuncio", ReplyAction="http://tempuri.org/IServiceAlemanha/UpdateAnuncioResponse")]
        void UpdateAnuncio(int id, MvcTIC_IT.ServiceRefAlemanha.AnuncioModel procura, MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/UpdateAnuncioDescricao", ReplyAction="http://tempuri.org/IServiceAlemanha/UpdateAnuncioDescricaoResponse")]
        void UpdateAnuncioDescricao(int id, MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/Search", ReplyAction="http://tempuri.org/IServiceAlemanha/SearchResponse")]
        MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel[] Search(MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel collection, int idiomacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAllAnuncios", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAllAnunciosResponse")]
        MvcTIC_IT.ServiceRefAlemanha.anuncio[] GetAllAnuncios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAlemanha/GetAllAnunciosByIdentidade", ReplyAction="http://tempuri.org/IServiceAlemanha/GetAllAnunciosByIdentidadeResponse")]
        MvcTIC_IT.ServiceRefAlemanha.anuncio[] GetAllAnunciosByIdentidade(string user);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StreamData {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Conteudo;
        
        public StreamData() {
        }
        
        public StreamData(string Codigo, System.IO.Stream Conteudo) {
            this.Codigo = Codigo;
            this.Conteudo = Conteudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        public UploadResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAlemanhaChannel : MvcTIC_IT.ServiceRefAlemanha.IServiceAlemanha, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAlemanhaClient : System.ServiceModel.ClientBase<MvcTIC_IT.ServiceRefAlemanha.IServiceAlemanha>, MvcTIC_IT.ServiceRefAlemanha.IServiceAlemanha {
        
        public ServiceAlemanhaClient() {
        }
        
        public ServiceAlemanhaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAlemanhaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAlemanhaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAlemanhaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.CompositeType GetDataUsingDataContract(MvcTIC_IT.ServiceRefAlemanha.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public int AddAnuncioModel(MvcTIC_IT.ServiceRefAlemanha.AnuncioModel anuncio) {
            return base.Channel.AddAnuncioModel(anuncio);
        }
        
        public bool AddDescricao(MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc) {
            return base.Channel.AddDescricao(desc);
        }
        
        public int GetIdioma_ID(string idiomacode) {
            return base.Channel.GetIdioma_ID(idiomacode);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.empresa[] GetAllEmpresaByID(string identidade) {
            return base.Channel.GetAllEmpresaByID(identidade);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[] GetAllAnunciosID(string idiomacode) {
            return base.Channel.GetAllAnunciosID(idiomacode);
        }
        
        public void UpdateVisitasAnuncioPortugal(int id) {
            base.Channel.UpdateVisitasAnuncioPortugal(id);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.anuncio GetAnunciosProcuraIndexByID(int id) {
            return base.Channel.GetAnunciosProcuraIndexByID(id);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.anunciodesc GetAnunciosDescProcuraIndexByIDAndLangCode(int id, string lang) {
            return base.Channel.GetAnunciosDescProcuraIndexByIDAndLangCode(id, lang);
        }
        
        public int GetCountIdiomas(int id) {
            return base.Channel.GetCountIdiomas(id);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.anunciodesc[] GetAnunciosDescProcuraIndexByIDALL(int id) {
            return base.Channel.GetAnunciosDescProcuraIndexByIDALL(id);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.PortugalViewModel[] GetAnunciosIndexByIdentidade(string user, string idiomacode) {
            return base.Channel.GetAnunciosIndexByIdentidade(user, idiomacode);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.empresa GetAllEmpresaByEmpresaID(int empresa_id) {
            return base.Channel.GetAllEmpresaByEmpresaID(empresa_id);
        }
        
        public int AddEmpresa(MvcTIC_IT.ServiceRefAlemanha.EmpresaModel desc) {
            return base.Channel.AddEmpresa(desc);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcTIC_IT.ServiceRefAlemanha.UploadResponse MvcTIC_IT.ServiceRefAlemanha.IServiceAlemanha.Upload(MvcTIC_IT.ServiceRefAlemanha.StreamData request) {
            return base.Channel.Upload(request);
        }
        
        public void Upload(string Codigo, System.IO.Stream Conteudo) {
            MvcTIC_IT.ServiceRefAlemanha.StreamData inValue = new MvcTIC_IT.ServiceRefAlemanha.StreamData();
            inValue.Codigo = Codigo;
            inValue.Conteudo = Conteudo;
            MvcTIC_IT.ServiceRefAlemanha.UploadResponse retVal = ((MvcTIC_IT.ServiceRefAlemanha.IServiceAlemanha)(this)).Upload(inValue);
        }
        
        public void UpdateImage_file(int id, string file_name_fto) {
            base.Channel.UpdateImage_file(id, file_name_fto);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.empresa[] GetEmpresasIndexByIdentidade(string user) {
            return base.Channel.GetEmpresasIndexByIdentidade(user);
        }
        
        public void UpdateEmpresa(int id, MvcTIC_IT.ServiceRefAlemanha.EmpresaModel desc) {
            base.Channel.UpdateEmpresa(id, desc);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.empresa GetEmpresaIndexByID(int id) {
            return base.Channel.GetEmpresaIndexByID(id);
        }
        
        public void DeleteEmpresa(int id) {
            base.Channel.DeleteEmpresa(id);
        }
        
        public void DeleteAnuncio(int id) {
            base.Channel.DeleteAnuncio(id);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.empresa[] GetEmpresasTodasasEmpresas() {
            return base.Channel.GetEmpresasTodasasEmpresas();
        }
        
        public void UpdateAnuncio(int id, MvcTIC_IT.ServiceRefAlemanha.AnuncioModel procura, MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc, string lang) {
            base.Channel.UpdateAnuncio(id, procura, desc, lang);
        }
        
        public void UpdateAnuncioDescricao(int id, MvcTIC_IT.ServiceRefAlemanha.DescricaoModel desc, string lang) {
            base.Channel.UpdateAnuncioDescricao(id, desc, lang);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel[] Search(MvcTIC_IT.ServiceRefAlemanha.SearchPortugalViewModel collection, int idiomacode) {
            return base.Channel.Search(collection, idiomacode);
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.anuncio[] GetAllAnuncios() {
            return base.Channel.GetAllAnuncios();
        }
        
        public MvcTIC_IT.ServiceRefAlemanha.anuncio[] GetAllAnunciosByIdentidade(string user) {
            return base.Channel.GetAllAnunciosByIdentidade(user);
        }
    }
}
