//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Portugal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portugal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTIC_IT.Resources.Views.Portugal.Portugal", typeof(Portugal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string apagado {
            get {
                return ResourceManager.GetString("apagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string apagar {
            get {
                return ResourceManager.GetString("apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string apagartemacerteza {
            get {
                return ResourceManager.GetString("apagartemacerteza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create job offer.
        /// </summary>
        public static string criaoferta {
            get {
                return ResourceManager.GetString("criaoferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly Saved.
        /// </summary>
        public static string gravado {
            get {
                return ResourceManager.GetString("gravado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string gravar {
            get {
                return ResourceManager.GetString("gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location.
        /// </summary>
        public static string local_de_trabalho {
            get {
                return ResourceManager.GetString("local_de_trabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        public static string naoharegistos {
            get {
                return ResourceManager.GetString("naoharegistos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Translated to English.
        /// </summary>
        public static string naotraduzido {
            get {
                return ResourceManager.GetString("naotraduzido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records.
        /// </summary>
        public static string numerototalregistos {
            get {
                return ResourceManager.GetString("numerototalregistos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of visits.
        /// </summary>
        public static string numvisitas {
            get {
                return ResourceManager.GetString("numvisitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string pesquisar {
            get {
                return ResourceManager.GetString("pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string salario {
            get {
                return ResourceManager.GetString("salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string traduzir {
            get {
                return ResourceManager.GetString("traduzir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new job offer on itjobs.dinispt.com.
        /// </summary>
        public static string viewbagtittlecreate {
            get {
                return ResourceManager.GetString("viewbagtittlecreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string volta {
            get {
                return ResourceManager.GetString("volta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string voltaparalista {
            get {
                return ResourceManager.GetString("voltaparalista", resourceCulture);
            }
        }
    }
}
