//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTIC_IT.Resources.Views.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Germany.
        /// </summary>
        public static string geriralemanha {
            get {
                return ResourceManager.GetString("geriralemanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Spain.
        /// </summary>
        public static string gerirespanha {
            get {
                return ResourceManager.GetString("gerirespanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage France.
        /// </summary>
        public static string gerirfrance {
            get {
                return ResourceManager.GetString("gerirfrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my SpecialOne-Jobs.
        /// </summary>
        public static string gerirmeuspecialone {
            get {
                return ResourceManager.GetString("gerirmeuspecialone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Portugal.
        /// </summary>
        public static string gerirportugal {
            get {
                return ResourceManager.GetString("gerirportugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage UK.
        /// </summary>
        public static string geriruk {
            get {
                return ResourceManager.GetString("geriruk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage World.
        /// </summary>
        public static string gerirworld {
            get {
                return ResourceManager.GetString("gerirworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic.it add jobs offers for free.
        /// </summary>
        public static string jobstitle {
            get {
                return ResourceManager.GetString("jobstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My SpecialOne-Jobs.
        /// </summary>
        public static string meuspecialone {
            get {
                return ResourceManager.GetString("meuspecialone", resourceCulture);
            }
        }
    }
}
